COMMONSENSE_MAPPING = {'Antonym': 'has antonym', 
	'AtLocation': 'is at location', 
	'CapableOf': 'is capable of', 
	'Causes': 'causes', 
	'CausesDesire': 'causes desire', 
	'CreatedBy': 'is created by', 
	'DefinedAs': 'defined as', 
	'DerivedFrom': 'is derived from', 
	'Desires': 'desires', 
	'DistinctFrom': 'is distinct from', 
	'Entails': 'entails', 
	'EtymologicallyDerivedFrom': 'is etymologically derived from', 
	'EtymologicallyRelatedTo': 'is etymologically related to',
	'ExcludesFE': 'excludes frame element', 
	'FormOf': 'is a form of', 
	'HasA': 'has a', 
	'HasContext': 'has context', 
	'HasFirstSubevent': 'has first subevent', 
	'HasFrameElement': 'has frame element',
	'HasInstance': 'has instance',
	'HasLastSubevent': 'has last subevent',
	'HasLexicalUnit': 'has lexical unit',
	'HasPrerequisite': 'has prerequisite', 
	'HasProperty': 'has property',
	'HasSemType': 'has semantic type',
	'HasSubevent': 'has subevent',
	'HasSubframe': 'has subframe', 
	'InstanceOf': 'is an instance of', 
	'IsA': 'is a',
	'IsCausativeOf': 'is causative of',
	'IsInchoativeOf': 'is inchoative of',
	'IsInheritedBy': 'is inherited by',
	'IsPerspectivizedIn': 'is perspectivized in',
	'IsPOSFormOf': 'is a part-of-speech form of',
	'IsPrecededBy': 'is preceded by',
	'IsUsedBy': 'is used by',
	'LocatedNear': 'is located near', 
	'MadeOf': 'is made of', 
	'MannerOf': 'is a manner of', 
	'MotivatedByGoal': 'is motivated by goal',
	'object': 'object',
	'OMWordnetOffset': 'wordnet offset', 
	'NotCapableOf': 'is not capable of', 
	'NotDesires': 'does not desire', 
	'NotHasProperty': 'does not have property', 
	'PartOf': 'is part of', 
	'PartOfSpeech': 'has part-of-speech',
	'PerspectiveOn': 'has perspective on',
	'POSForm': 'has part-of-speech form',
	'Precedes': 'precedes',
	'PWordnetSynset': 'is a wordnet synset',
	'ReceivesAction': 'receives action', 
	'ReframingMapping': 'reframies mapping',
	'RelatedTo': 'relates to', 
	'RequiresFE': 'requires frame element',
	'subject': 'subject',
	'SeeAlso': 'see also',
	'SimilarTo': 'is similar to', 
	'subClassOf': 'is a subclass of',
	'SubframeOf': 'is a subframe of',
	'SubType': 'has subtype',
	'SuperType': 'has supertype',
	'SymbolOf': 'is a symbol of', 
	'Synonym': 'has synonym', 
	'UsedFor': 'is used for',
	'Uses': 'uses', 
        'DesireOf': 'desire of',
        'InheritsFrom': 'inherits from',
        'LocationOfAction': 'location of action',
	'dbpedia/capital': 'capital', 
	'dbpedia/field': 'field', 
	'dbpedia/genre': 'genre', 
	'dbpedia/genus': 'genus', 
	'dbpedia/influencedBy': 'influenced by', 
	'dbpedia/knownFor': 'known for', 
	'dbpedia/language': 'language', 
	'dbpedia/leader': 'leader', 
	'dbpedia/occupation': 'occupation', 
	'dbpedia/product': 'product',
	'xAttr': 'has attribute',
	'xEffect': 'has effect',
	'xIntent': 'intents',
	'xNeed': 'needs',
	'xReact': 'reacts',
	'xWant': 'wants',
	'oEffect': 'has effect on others',
	'oReact': 'others react',
	'oWant': 'others want'}
